global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Kolme.API.Models;
global using Kolme.API.DTOs;
global using Kolme.API.Data;
